### ISSUE TITLE
[Bug] LMS detected

### ISSUE THREAD

**Issue by luximus-hunter** [SpikeHD/rsRPC#1]
**Describe the bug**
`lms.exe` gets detected as "Last Man Standing", when in actuallity it is "Intel Local Machine Service"

**To Reproduce**
1. Enable rsRPC
2. Enable arRPC plugin
3. "**Playing** Last Man Standing"

**Expected behavior**
RPC should be empty

**Screenshots**
![image](https://github.com/SpikeHD/rsRPC/assets/49814847/d48a35f2-a6e7-43c0-8f21-d37247f58965)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v1.2.0

**Comment by SpikeHD** [comment]
I have decided I will just be removing this game from the detectable games list for now LOL

**Comment by luximus-hunter** [comment]
Yay!
