### ISSUE TITLE
 rsRPC can't display the currently playing music in VLC media player

### ISSUE THREAD

**Issue by jonm58** [SpikeHD/rsRPC#4]
https://github.com/greendoescode/vlc-rpc

Hello,
The rsRPC does not display the currently playing music, but works fine with arRPC.
Can you fix it?
Thank you for your help.

**Comment by SpikeHD** [comment]
While it worked for me originally, it did lead me down some paths to fix some other bugs. `v0.20.0` will be released once the GitHub actions job is done shortly, let me know if that improves things :)

![image](https://github.com/user-attachments/assets/cd3ed8aa-d755-4f8c-9b36-32e33d199fbe)
(ignore the missing album cover, that is a bug in [shelteRPC](https://github.com/SpikeHD/shelter-plugins/issues/41))

**Comment by jonm58** [comment]
![图片](https://github.com/user-attachments/assets/76f3d44a-55d1-4c99-bd98-df9c225b5433)

thank you.
rsRPC v0.20.0 works very good.
