### ISSUE TITLE
rsRPC shows that AIMP is currently playing music for a little too long

### ISSUE THREAD

**Issue by jonm58** [SpikeHD/rsRPC#5]
Hello,
The rsRPC shows that the currently playing music **is a bit long**, but it is normal when using arRPC.
Can you solve this problem?
Thank you for your help.

https://github.com/Exle/aimp-discord-presence/releases/tag/1.1.0.16

![AIMP_Discord_rsrpc](https://github.com/user-attachments/assets/7d5b9b0e-1dc8-4095-9cf0-577c3cb582d8)

**Comment by SpikeHD** [comment]
In any of the `Received message: ` logs where it outputs the activity, what is the value of the `timestamps: { start }` section? In my case, it output `"timestamps":{"start":1733196411}` which is a very normal timestamp (can be converted using a site like this: https://www.epochconverter.com/). Is it giving you weird numbers?

**Comment by SpikeHD** [comment]
Ah nevermind, I looked at arRPC for reference and they [convert the timestamps](https://github.com/OpenAsar/arrpc/blob/5aadc307cb9bf4479f0a12364a253b07a77ace22/src/server.js#L118)

**Comment by SpikeHD** [comment]
Should be fixed in fb940c4d4b6f39b1753585ce42a27514cf328549, try an [actions build](https://github.com/SpikeHD/rsRPC/actions/runs/12132532174) and lemme know if it fixes it 👍

**Comment by jonm58** [comment]
Thanks,actions build fixed it 👍.
![图片](https://github.com/user-attachments/assets/e22bdeff-49a1-45a2-9919-67548f54b50c)
